### ISSUE TITLE
[Docs] Lifecycle: Upgrading Meshery Operator

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-operator#148]
**Current Behavior**
The Meshery Operator has some documentation on the fact that it manages the upgrade of it's components - https://docs.meshery.io/guides/upgrade#versioning-of-meshery-components.

**Desired Behavior**
Documentation is needed on what the user needs to do to upgrade the Meshery Operator, if anything.

**Comment by leecalcote** [comment]
@metonymic-smokey could you tackle this?

**Comment by metonymic-smokey** [comment]
@leecalcote sorry for the delay, I'd accidentally missed this issue.
I'll open a draft in about a week(exams going on right now)
