### ISSUE TITLE
Port meshkit errors

### ISSUE THREAD

**Issue by kumarabd** [meshery/meshery-operator#170]
**Current Behavior**
Port meshkit errors to the new error utility function. Instructions covered here,
https://github.com/layer5io/meshkit/pull/48

---
**Resources**

**Alternatives / Additional Context**

**Comment by Shreyas220** [comment]
@kumarabd please assign it to me :)

**Comment by Shreyas220** [comment]
@kumarabd can you tell me more on this
because from what I see this issue is already resolved

**Comment by kumarabd** [comment]
> @kumarabd can you tell me more on this
> because from what I see this issue is already resolved

@Shreyas220  it has a reference of a different closed issue. This issue is still open and yours to work on.
