### ISSUE TITLE
Move error util to a new directory

### ISSUE THREAD

**Issue by kumarabd** [meshery/meshery-operator#180]
```suggestion
	go run github.com/layer5io/meshkit/cmd/errorutil -d . update -i ./helpers -o ./helpers
```
Also move the errorutil files to the new directory

_Originally posted by @DelusionalOptimist in https://github.com/meshery/meshery-operator/pull/176#discussion_r661831801_

**Comment by kumarabd** [comment]
@DelusionalOptimist Will you be able to pick this item?

**Comment by DelusionalOptimist** [comment]
Sure @kumarabd :slightly_smiling_face:
