### ISSUE TITLE
[CI] add error codes utility runner workflow

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery-operator#191]
**Current Behaviour**
Error codes utility runner workflow is not present.

**Desired Behavious**
Add the error codes utility runner workflow.

**Instructions in https://github.com/meshery/meshery-linkerd/issues/213**

**Comment by bariqhibat** [comment]
I can also help this if it's similar

**Comment by nehaLohia27** [comment]
@DelusionalOptimist @bariqhibat Can i also work on this issue ?

**Comment by DelusionalOptimist** [comment]
@bariqhibat @nehaLohia27 Please share this issue. :smile:

**Comment by bariqhibat** [comment]
Sure, you can do this instead:) @nehaLohia27 

I have a similar task in meshery-istio too.
