### ISSUE TITLE
Can't use meshery on k3s/klipper-lb

### ISSUE THREAD

**Issue by keithmattix** [meshery/meshery-operator#210]
**Description**
Due to meshery-broker's use of `hostPort` in its `StatefulSet` manifest, I'm currently running into a race condition between [klipper-lb](https://github.com/k3s-io/klipper-lb)'s autocreated load balancer pod and `meshery-broker-0` since both are trying to claim the same host port. In the vast majority of scenarios, host ports are unnecessary for pods; is there a reason meshery-operator and meshery-broker use them?

**Expected Behavior**
Meshery-operator and meshery-broker pods should not use `hostPort`

**Screenshots**

**Environment:**
 - OS: MacOS

 - Device: Kubernetes k3s/k3d

**Comment by leecalcote** [comment]
Host port is no longer used as of Meshery v0.5.71. @keithmattix, when convenient, will you kindly confirm this fix addresses the issue?

**Comment by keithmattix** [comment]
I'm still running into port conflicts. I think the issue is with the `Broker` CRD being listened to by meshery-operator. Notice the `hostPort`s in use [here](https://github.com/meshery/meshery-operator/blob/43a3ccc23e7dd8f4dc8ba56d9e9477651dc8d913/pkg/broker/resources.go#L174)

**Comment by Aisuko** [comment]
Hi @keithmattix Are there any else issues we need to fix? Please help to confirm the PR already fixed this issue.

**Comment by keithmattix** [comment]
The main thing is in my previous message; when creating pods, the meshery-broker assigns hostPorts to those pods. You can see the `hostPort` usage in this Go code: https://github.com/meshery/meshery-operator/blob/master/pkg/broker/resources.go#L174 

If those host ports can be removed, then this issue will be solved

**Comment by Aisuko** [comment]
Thanks for your detail.

**Comment by leecalcote** [comment]
Possible fix here: https://github.com/meshery/meshery-operator/pull/250

**Comment by leecalcote** [comment]
// @kumarabd

**Comment by Aisuko** [comment]
We can close this after we got confirmed.

**Comment by keithmattix** [comment]
Works like a charm - thanks for the good work!
