### ISSUE TITLE
List Meshery Operator in Operator Hub

### ISSUE THREAD

**Issue by iamsdas** [meshery/meshery-operator#220]
#### Current Behavior

Currently, Meshery Operator is not listed in OperatorHub.io

#### Desired Behavior

It should be [published](https://operatorhub.io/contribute#Publish-your-Operator-on-OperatorHub.io)  on OperatorHub.io.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@iamsdas will you add this item to the Meshery Build and Release meeting and provide an update on progress?

**Comment by leecalcote** [comment]
@iamsdas any luck so far?

**Comment by iamsdas** [comment]
Sorry, I was really busy for the past 2 weeks and did not get much time to look into it (also completely missed your previous message). I'll start with this tomorrow once my exams are over.

**Comment by iamsdas** [comment]
While generating the operator bundle (using `made bundle`) I am getting some issues / have some questions:

1. Initially it was giving some errors regarding deprecated versions. After running the upgrade command there were some changes to the `PROJECT` file, not sure if it will cause any issues.

 ```
WARN[0000] Config version 3-alpha has been stabilized as 3, and 3-alpha is no longer supported. Run `operator-sdk alpha config-3alpha-to-3` to upgrade your PROJECT config file to version 3
Error: error reading configuration: unable to load the configuration: unable to create config for version "3-alpha": version 3-alpha is not supported
```

2. The `make bundle` requires some inputs which I am not completely sure about. Can someone confirm the required inputs?
```
Display name for the operator (required):
> meshery-operator
Description for the operator (required):
> Meshery Operator is the multi-service mesh operator and implementation of MeshSync
Provider's name for the operator (required):
> Meshery
Any relevant URL for the provider name (optional):
> https://meshery.io/
Comma-separated list of keywords for your operator (required):
> meshery,meshery-operator,service-mesh
Comma-separated list of maintainers and their emails (e.g. 'name1:email1, name2:email2') (required):
>
```

3. After giving the required inputs, it gives me another error message. But the bundle is made successfully with an `All validation tests have completed successfully`. Is this a cause of concern?
```
Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/home/sdas/code/meshery-operator/config/manifests'
```

**Comment by iamsdas** [comment]
CC @DelusionalOptimist

**Comment by Aisuko** [comment]
Hi @iamsdas .   Could you help confirm that kustomize already installed on your environment?

**Comment by iamsdas** [comment]
Yup, I had run `make kustomize` to install it

**Comment by Aisuko** [comment]
Looks like a bug https://github.com/operator-framework/operator-sdk/issues/4575#issuecomment-785396141. I hit the same issue.

**Comment by Aisuko** [comment]
The version of `operator-sdk`

```
operator-sdk version: "v1.15.0", commit: "f6326e832a8a5e5453d0ad25e86714a0de2c0fc8", kubernetes version: "1.21", go version: "go1.16.10", GOOS: "linux", GOARCH: "amd64"
```

I'm trying to fix this.

**Comment by leecalcote** [comment]
Gents, some good progress here. 👍

**Comment by Aisuko** [comment]
Hi, @iamsdas, please help us list the operator in the Operator Hub, thanks.

**Comment by iamsdas** [comment]
I need someone to confirm the detail to be entered in this before I can proceed:
```
Display name for the operator (required):
> meshery-operator
Description for the operator (required):
> Meshery Operator is the multi-service mesh operator and implementation of MeshSync
Provider's name for the operator (required):
> Meshery
Any relevant URL for the provider name (optional):
> https://meshery.io/
Comma-separated list of keywords for your operator (required):
> meshery,meshery-operator,service-mesh
Comma-separated list of maintainers and their emails (e.g. 'name1:email1, name2:email2') (required):
>
```

**Comment by Aisuko** [comment]
> I need someone to confirm the detail to be entered in this before I can proceed:
> 
> ```
> Display name for the operator (required):
> > meshery-operator
> Description for the operator (required):
> > Meshery Operator is the multi-service mesh operator and implementation of MeshSync
> Provider's name for the operator (required):
> > Meshery
> Any relevant URL for the provider name (optional):
> > https://meshery.io/
> Comma-separated list of keywords for your operator (required):
> > meshery,meshery-operator,service-mesh
> Comma-separated list of maintainers and their emails (e.g. 'name1:email1, name2:email2') (required):
> >
> ```

Thank you, @iamsdas, for my personal it looks good, the Email address can be `community@meshery.io` with the name `Meshery Authors`. We use this on our Helm charts.

Hi @leecalcote, please help us confirm this.

**Comment by iamsdas** [comment]
It seems that the updated version of the repo has the required info in the `config/manifests/bases/meshery-operator.clusterserviceversion.yaml` file and the `make bundle` command uses it automatically.

**Comment by iamsdas** [comment]
So I think I'm mostly ready to send the PR. Final question:
Should I add a `ci.yml` file for reviewers? Basically every time someone sends a PR for the operator they will be added to the reviewer's list. If yes then who all should I add? And should I go ahead with the PR?

**Comment by iamsdas** [comment]
Btw this may be concerning
```
❯ operator-sdk bundle validate ./bundle/ --select-optional name=operatorhub
WARN[0000] Warning: Value : (meshery-operator.v0.0.1) csv.Spec.minKubeVersion is not informed. It is recommended you provide this information. Otherwise, it would mean that your operator project can be distributed and installed in any cluster version available, which is not necessarily the case for all projects. 
ERRO[0000] Error: Value : (meshery-operator.v0.0.1) csv.Spec.Icon elements should contain both data and mediatype 
```

**Comment by Aisuko** [comment]
> 

Hi @iamsdas, I miss your comment. Did you mean `dependabot.yaml` file ?  Please do that and request the review from @leecalcote https://github.com/meshery/meshery/issues/4889#issuecomment-1007307740

**Comment by Aisuko** [comment]
> So I think I'm mostly ready to send the PR. Final question:
> Should I add a `ci.yml` file for reviewers? Basically every time someone sends a PR for the operator they will be added to the reviewer's list. If yes then who all should I add? And should I go ahead with the PR?

Hi @iamsdas, I miss your comment. Did you mean `dependabot.yaml` file ?  Please do PR and request the review from @leecalcote https://github.com/meshery/meshery/issues/4889#issuecomment-1007307740

**Comment by Aisuko** [comment]
> csv.Spec.minKubeVersion is not informed.

I believe we need to configurate for the bundle, right? Let's try to fix this.

**Comment by leecalcote** [comment]
> > I need someone to confirm the detail to be entered in this before I can proceed:
> > ```
> > Display name for the operator (required):
> > > meshery-operator
> > Description for the operator (required):
> > > Meshery Operator is the multi-service mesh operator and implementation of MeshSync
> > Provider's name for the operator (required):
> > > Meshery
> > Any relevant URL for the provider name (optional):
> > > https://meshery.io/
> > Comma-separated list of keywords for your operator (required):
> > > meshery,meshery-operator,service-mesh
> > Comma-separated list of maintainers and their emails (e.g. 'name1:email1, name2:email2') (required):
> > >
> > ```
> 
> Thank you, @iamsdas, for my personal it looks good, the Email address can be `community@meshery.io` with the name `Meshery Authors`. We use this on our Helm charts.
> 
> Hi @leecalcote, please help us confirm this.

Looks good. 👍

**Comment by iamsdas** [comment]
> Hi @iamsdas, I miss your comment. Did you mean `dependabot.yaml` file ? Please do PR and request the review from @leecalcote [meshery/meshery#4889 (comment)](https://github.com/meshery/meshery/issues/4889#issuecomment-1007307740)

Actually, I am talking about the [ci.yaml](https://k8s-operatorhub.github.io/community-operators/operator-ci-yaml/) file. It would be used to setup reviews for PRs to the operator after it gets added.

**Comment by Aisuko** [comment]
> > Hi @iamsdas, I miss your comment. Did you mean `dependabot.yaml` file ? Please do PR and request the review from @leecalcote [meshery/meshery#4889 (comment)](https://github.com/meshery/meshery/issues/4889#issuecomment-1007307740)
> 
> Actually, I am talking about the [ci.yaml](https://k8s-operatorhub.github.io/community-operators/operator-ci-yaml/) file. It would be used to setup reviews for PRs to the operator after it gets listed.

Ok, I got your point now. Please do this.  cc @leecalcote

**Comment by Aisuko** [comment]
I believe that we do not need to set the `minikube` version due to our test cases will run on the real environment in `suit_test.go`(after I add some test cases).

But, for the `csv.spec.icon` we  must have it here. Due to if we push teh operator to the `operatorhub.io` we need to have a logo for it. Just like the `icon` in Helm charts' `charts` file.

So, we need to ping @leecalcote to get the confirm, which icon we can use for the `meshery-operator`. And add the address to the `icon` filed in this file.

![Screenshot 2022-01-18 at 6 50 59 PM](https://user-images.githubusercontent.com/8053949/149924355-d345aeaf-64a4-4eed-b4dc-21cf16232101.png)

**Comment by leecalcote** [comment]
@iamsdas @Aisuko, icons for Meshery Operator are here: https://meshery.io/brand

**Comment by Aisuko** [comment]
Hi @iamsdas , Any help here?

**Comment by Aisuko** [comment]
Hi @leecalcote , no worries sir. I will lead to this. Actually, we almost finish totally process.

**Comment by leecalcote** [comment]
Much appreciated, @Aisuko 👏

**Comment by Aisuko** [comment]
Close due to https://github.com/k8s-operatorhub/community-operators/pull/1204#event-6598398758
