### ISSUE TITLE
Update Slack.yml and add newcomer-alert workflow

### ISSUE THREAD

**Issue by cpepper96** [meshery/meshery-operator#233]
**Current Behavior**
Currently the slack.yml is outdated. Also there is no automated way of notifying the slack channel when a "good first issue" has been created.

**Desired Behavior**
Update slack.yml and add newcomer-alert.yml to the Github workflow. 

---
**Resources**
Add the updated slack.yml file and the newcomer-alert.yml file to the .github/workflow folder.

Files needed:
https://github.com/meshery/meshery-istio/blob/master/.github/workflows/slack.yml
https://github.com/layer5io/layer5/blob/master/.github/workflows/newcomers-alert.yml

**Comment by Ankita13-code** [comment]
Hi @cpepper96! I would like to take up this issue

**Comment by warunicorn19** [comment]
Please go ahead @Ankita13-code.

**Comment by Ankita13-code** [comment]
I have created a PR for this issue - https://github.com/meshery/meshery-operator/pull/235 
Please have a look @warunicorn19.
