### ISSUE TITLE
[Docs]The updation of shields is needed in README.md

### ISSUE THREAD

**Issue by Swapnil-Bhabal** [meshery/meshery-operator#240]
**Current State:**
Small updation of shields in README.md
![image](https://user-images.githubusercontent.com/61308713/146507762-ed0afd91-3ba0-4bac-941a-130f47e32272.png)

**Desired State:**
This is how it should look like
![image](https://user-images.githubusercontent.com/61308713/146507863-f844d6c5-373b-4e80-85c0-d5985b5abb20.png)

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Swapnil-Bhabal** [comment]
Kindly Assign this task to me

**Comment by Aisuko** [comment]
@Swapnil-Bhabal Thank you.  Feel free do a PR and related to this issue.
