### ISSUE TITLE
Add the BDD test framework for the operator.

### ISSUE THREAD

**Issue by Aisuko** [meshery/meshery-operator#252]
#### Current Behavior

No testcase here.

#### Desired Behavior

We need to add the BDD test framework and allow the contributor write the testcases for the operator.

And the testcase includes:

* CRDs API resources CURD
   * This is not mean we try to test the api-server of kubernetes, this is aim to test the version of resource is ok for the specific version of k8s
   * And the specific value (like length or type) would without pruning by the api-server before persistent to etcd
* The normal behavior of the controllers
* the util package that supports the suit test too.

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
+1
