### ISSUE TITLE
Incorporate "pipline" package into discovery tiers

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-operator#29]
**Current Behavior**
All fingerprinters run when MeshSync is invoked. They run without order of precedence defined or controlled sequence or concurrent operation defined.

**Desired Behavior**
Incorporate stages and steps of the pipeline package into design of MeshSync discovery process; create discovery tiers.

---
**Resources**
 - https://github.com/myntra/pipeline

**Comment by leecalcote** [comment]
Incorporated. @kalradev any documentation that we want to capture as part of the closing of this issue?

**Comment by leecalcote** [comment]
Gents, 

Will you perform a quick update of the MeshSync docs prior to July 31st?

**Comment by kumarabd** [comment]
> Gents,
> 
> Will you perform a quick update of the MeshSync docs prior to July 31st?

Updated them with log viewer and interactive terminal
