### ISSUE TITLE
Prevent MeshSync from restarting unnecessarily on initial deployment

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-operator#290]
#### Current Behavior
When Meshery Operator deploys MeshSync, it takes two restarts of MeshSync before it will start running.

#### Desired Behavior
No restarts.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Revolyssup** [comment]
@leecalcote It is because it waits for the broker. If the broker isn't available then the binary exits, and pod is stuck in crashloopbackoff untill the broker is available.

**Comment by Revolyssup** [comment]
> @leecalcote It is because it waits for the broker. If the broker isn't available then the binary exits, and pod is stuck in crashloopbackoff untill the broker is available.

If we were to change this behaviour, we would also do the same thing. Use something like exponentialbackoff to keep retrying inside the binary when the NATS connection fails. Kubernetes replicaset controller does this for us. So do we want to add code here?

**Comment by leecalcote** [comment]
No, we don't want to add code here. We want to use an existing capability of either kubebuilder or of Kubernetes to facilitate readiness, dependency, and boot order.
