### ISSUE TITLE
Unable to uninstall Meshery Operator from second cluster

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-operator#332]
#### Current Behavior
With Meshery Server connected to a second or third cluster, when a user invokes the button on Meshery UI to remove Meshery Operator from one of those clusters, the following error is received and the operator is not removed.

#### Screenshots/Logs
```
time="2022-07-20T22:00:42Z" level=error msg="uninstall: Release not loaded: meshery-operator: release: not found" app=meshery code=2155 probable-cause="Kubernetes cluster might not be connected.Leftover resources from partial install" severity=2 short-description="Error occurred while applying Helm Chart" suggested-remediation="Try reinstalling.Try reconnecting your kubernetes cluster.Clean up artifacts from preinstalled helm release manually"
```

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@MUzairS15 fyi. We're unable to uninstall from the first and only cluster at this point.

```
ERRO[2022-08-05T16:19:41-05:00] uninstall: Release not loaded: meshery-operator: release: not found  app=meshery code=2155 probable-cause="Kubernetes cluster might not be connected.Leftover resources from partial install" severity=2 short-description="Error occurred while applying Helm Chart" suggested-remediation="Try reinstalling.Try reconnecting your kubernetes cluster.Clean up artifacts from preinstalled helm release manually"
```

**Comment by MUzairS15** [comment]
> @Aisuko this issue has to do with the fact that there are discrepancies between the different Helm charts, I believe.

@leecalcote This is not the case, because though there are discrepancies, we install and uninstall the same helm chart.
https://github.com/meshery/meshkit/pull/202 This is the fix for this issue.

But you are tight, we must ensure `meshery-operator` chart is same everywhere.
