### ISSUE TITLE
[Docs] Broken image link in README

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-operator#341]
#### Current State
<img width="923" alt="Screen Shot 2022-08-17 at 8 12 40 AM" src="https://user-images.githubusercontent.com/7570704/185143079-ed0581c2-450f-473c-af70-67dbb3c761b0.png">

#### Desired State
Link should be updated with new image location.

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by rohannair11** [comment]
Can I try to work on this ?

**Comment by leecalcote** [comment]
Thanks, @rohannair11

**Comment by rohannair11** [comment]
how do I view the changes locally ?

**Comment by KrishAryan** [comment]
@rohannair11 follow the steps:-
1.)fork the repo 
2.)In your forked repo scroll down to readme
![image](https://user-images.githubusercontent.com/64402456/185160485-f101216d-f093-4d13-8108-9b36daf91bdb.png)
3.)In the top-right of readme there is edit button click it
4.)Edit the code and the check the changes with the preview button

**Comment by rohannair11** [comment]
yeah i'm following the same steps, but I what image should I fix the broken text with?

**Comment by rohannair11** [comment]
hey I opened a pr on my forked branch I guess, how should I make this PR show up on the main repo?

**Comment by KrishAryan** [comment]
I think you are not commiting the changes...scroll down and commit the changes.

**Comment by rohannair11** [comment]
@KrishAryan
![Screenshot 2022-08-18 145817](https://user-images.githubusercontent.com/42870265/185361660-521e2902-5ce5-4cd6-a0ef-43ecd71a347e.png)
It shows that the PR has been merged but that's probably to my fork instead of the main repo

**Comment by KrishAryan** [comment]
I think you made a new branch and merged the changes in your own branch. Merging should be from your fork to the main repo of  meshery-operator

**Comment by KrishAryan** [comment]
I think it would be better to ask for help in a slack thread since you can get help from many people there.

**Comment by acald-creator** [comment]
@rohannair11 I realized that we are in different time zone, but if you post in the Slack thread, we will be able to help out to get your PR in. You have the PR merged with your forked repository.

**Comment by nik132-eng** [comment]
if this issue is live I want to contribute to it. @leecalcote can you assign me, please?

**Comment by K0more** [comment]
@KrishAryan does this issue still exist? 🤔

**Comment by KrishAryan** [comment]
I think this issue is solved as there are no broken images right now

**Comment by acald-creator** [comment]
Fixed per PR https://github.com/meshery/meshery-operator/pull/373
