### ISSUE TITLE
[Refactor] Ginkgo test suite

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery-operator#359]
#### Current Behavior

This project is using Ginkgo v1, Ginkgo has migrated to v2, which means the tests will be failing.

This can also assist in the Go 1.19 upgrade, however, it is not a dependent on the Go version.

In order to make this upgrade, here are the steps to get started:

```bash
# Grab the module
go get github.com/onsi/ginkgo/v2

# Install the necessary packages first
go get github.com/onsi/ginkgo/v2/ginkgo/labels@v2.1.6
go get github.com/onsi/ginkgo/v2/ginkgo/internal@v2.1.6
go get github.com/onsi/ginkgo/v2/ginkgo/generators@v2.1.6

# Finish the installation for Ginkgo
go install github.com/onsi/ginkgo/v2/ginkgo
```

Rename `github.com/onsi/ginkgo` to `github.com/onsi/ginkgo/v2`

Then run `go test ./...`

Example of output

```bash
go test ./...
?   	github.com/layer5io/meshery-operator	[no test files]
# github.com/layer5io/meshery-operator/api/v1alpha1 [github.com/layer5io/meshery-operator/api/v1alpha1.test]
api/v1alpha1/suite_test.go:48:14: cannot use printer.NewlineReporter{} (value of type printer.NewlineReporter) as type "github.com/onsi/ginkgo/v2/reporters".DeprecatedReporter in array or slice literal:
	printer.NewlineReporter does not implement "github.com/onsi/ginkgo/v2/reporters".DeprecatedReporter (wrong type for AfterSuiteDidRun method)
		have AfterSuiteDidRun(setupSummary *"github.com/onsi/ginkgo/types".SetupSummary)
		want AfterSuiteDidRun(setupSummary *"github.com/onsi/ginkgo/v2/types".DeprecatedSetupSummary)
api/v1alpha1/suite_test.go:82:4: too many arguments in call to BeforeSuite
	have (func(done "github.com/onsi/ginkgo/v2/internal".Done), number)
	want (func())
FAIL	github.com/layer5io/meshery-operator/api/v1alpha1 [build failed]
# github.com/layer5io/meshery-operator/controllers [github.com/layer5io/meshery-operator/controllers.test]
controllers/suite_test.go:49:14: cannot use printer.NewlineReporter{} (value of type printer.NewlineReporter) as type "github.com/onsi/ginkgo/v2/reporters".DeprecatedReporter in array or slice literal:
	printer.NewlineReporter does not implement "github.com/onsi/ginkgo/v2/reporters".DeprecatedReporter (wrong type for AfterSuiteDidRun method)
		have AfterSuiteDidRun(setupSummary *"github.com/onsi/ginkgo/types".SetupSummary)
		want AfterSuiteDidRun(setupSummary *"github.com/onsi/ginkgo/v2/types".DeprecatedSetupSummary)
controllers/suite_test.go:86:4: too many arguments in call to BeforeSuite
	have (func(done "github.com/onsi/ginkgo/v2/internal".Done), number)
	want (func())
FAIL	github.com/layer5io/meshery-operator/controllers [build failed]
?   	github.com/layer5io/meshery-operator/pkg/broker	[no test files]
?   	github.com/layer5io/meshery-operator/pkg/client	[no test files]
?   	github.com/layer5io/meshery-operator/pkg/client/v1alpha1	[no test files]
?   	github.com/layer5io/meshery-operator/pkg/meshsync	[no test files]
FAIL
```

#### Expected Behavior

`go test ./...` should complete successfully

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by acald-creator** [comment]
I'll add the changes to the test suite in the Go 1.19 PR

**Comment by acald-creator** [comment]
// update

Will work on the test suite, now that the project has been upgraded to use Go 1.19

**Comment by leecalcote** [comment]
Oh, excellent. OK. 👍
