### ISSUE TITLE
[Docs] broken image in readme

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-operator#371]
#### Current State
There’s a broken image in this repository’s readme.md. 

#### Desired State

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by NPDebs** [comment]
Hi, Mr @leecalcote . Can I pick this one up? 👀

**Comment by nik132-eng** [comment]
Hello @leecalcote, looking for my first contribution to Layer5 / meshery. can I get this issue pls

**Comment by leecalcote** [comment]
Thank you for picking this one up, @NPDebs 👏

**Comment by leecalcote** [comment]
@nik132-eng ok, no sweat. We’ll be opening up many new issues this week in prep for Hacktoberfest. 👍

**Comment by NPDebs** [comment]
My pleasure! 😊🚀

Thank you right back.
