### ISSUE TITLE
[feat] Update Logging in Meshery Operator

### ISSUE THREAD

**Issue by acald-creator** [meshery/meshery-operator#437]
#### Current Behavior

Here is the output from running Meshery Operator locally.

```bash
INFO[2023-02-23T12:18:57-06:00] Metrics server is starting to listen          app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] controllermeshsynccontrollerGroupmeshery.layer5.iocontrollerKindMeshSync  app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] controllerbrokercontrollerGroupmeshery.layer5.iocontrollerKindBroker  app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] starting manager                              app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] path/metrics                                  app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] kindmetricsaddr[::]:8080                      app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] Starting server                               app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] Starting EventSource                          app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] Starting Controller                           app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] Starting EventSource                          app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] Starting Controller                           app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] Starting workers                              app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] Brokermeshery/meshery-brokernamespacemesherynamemeshery-broker  app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] reconcileID5d7491cb-b1c9-48a8-9151-e7b76c27ef24  app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] controllerBroker                              app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] namespacemeshery/meshery-broker               app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] Starting workers                              app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] Reconciling broker                            app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] MeshSyncmeshery/meshery-meshsyncnamespacemesherynamemeshery-meshsync  app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] reconcileID13efdfa7-2677-4ff7-83eb-f1a8f7acfe07  app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] controllerMeshSync                            app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] namespacemeshery/meshery-meshsync             app=meshery-operator
INFO[2023-02-23T12:18:57-06:00] Reconciling MeshSync                          app=meshery-operator
```

#### Desired Behavior

It would be nice if we can update the logging format, and space out some of the words, and make it readable.

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by devkapilbansal** [comment]
Hi @acald-creator I would like to provide a fix for this

**Comment by Aisuko** [comment]
@devkapilbansal Hi, feel free to work on this issue.

**Comment by rjsanghamitra** [comment]
Hello!
I tried updating the logging format. But I assume that it requires changes in other repositories. Am I right?
The following is the output after I made some changes.
![image](https://user-images.githubusercontent.com/94747124/228932671-961e37b8-9ed0-400e-aac7-2ad3111b15e6.png)

**Comment by Aisuko** [comment]
> 

Hi, @rjsanghamitra . I believe you are right. There may need some changes in other repo.

**Comment by rjsanghamitra** [comment]
Thank you @Aisuko. So shall I go ahead with that or is there any other solution to this issue?

**Comment by Aisuko** [comment]
I believe you can do a PR first and show your PR scope if you have made some effects.

**Comment by rjsanghamitra** [comment]
Okay, thanks!

**Comment by Aisuko** [comment]
No worries.
