### ISSUE TITLE
[CI] Increase the test coverage for the code to 60%

### ISSUE THREAD

**Issue by Aisuko** [meshery/meshery-operator#463]
#### Current Behavior

[![codecov](https://codecov.io/gh/meshery/meshery-operator/branch/master/graph/badge.svg?token=TJZ2L4JHSA)](https://codecov.io/gh/meshery/meshery-operator)

#### Desired Behavior

We need to increase the test coverage of code, it will keep the code quality in a high level and give us more confidence to merge new PRs.

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Aisuko** [comment]
remove

**Comment by Aisuko** [comment]
remove

**Comment by Aisuko** [comment]
remove

**Comment by Aisuko** [comment]
remove

**Comment by ayushrakesh** [comment]
@Aisuko @sandramsc any tasks are still left for this issue?

**Comment by Aisuko** [comment]
Hi @ayushrakesh Feel free to pick up other issues. I think this issue can be closed now. The test coverage is 53%. which enough for us.
