### ISSUE TITLE
Remove no-useful CI processes in this repo

### ISSUE THREAD

**Issue by Aisuko** [meshery/meshery-operator#465]
#### Current Behavior

According to  PR https://github.com/meshery/meshery-operator/pull/457, we have removed `envtest` in more detail please see that PR. 

Currently, the script is still setup `envtest` environment, and it can cause the CI process very long(> 3minutes). So, we need to remove these scripts.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by jinronga** [comment]
@Aisuko  I  would like to try this one.
