### ISSUE TITLE
Add the code coverage for this repo

### ISSUE THREAD

**Issue by Aisuko** [meshery/meshery-operator#467]
#### Current Behavior

We do not have test coverage for the code, it is hard for us to review and merge the PR with the same code quality. And we want to increase the code quality. So, we need to add coverage to the repo.

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Wonderful

**Comment by Aisuko** [comment]
This issue is related to PR #468

**Comment by Aisuko** [comment]
Closing by PR #471
