### ISSUE TITLE
[CI] The welcome picture is missing in this repo

### ISSUE THREAD

**Issue by Aisuko** [meshery/meshery-operator#469]
#### Current Behavior

The welcome picture is missing in this repo

#### Desired Behavior

Make sure the welcome picture is working well.

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by s3690691** [comment]
Hi, Aisuko. Can you assign this issue to me? I would like to handle this issue.

**Comment by leecalcote** [comment]
Or @anshgoyalevil might chime in.

**Comment by anshgoyalevil** [comment]
@Aisuko 

Could you please specify the issue description a bit more. Since, the welcome pictures are already present in this repo at https://github.com/meshery/meshery-operator/tree/master/.github/welcome

**Comment by Aisuko** [comment]
> @Aisuko
> 
> Could you please specify the issue description a bit more. Since, the welcome pictures are already present in this repo at https://github.com/meshery/meshery-operator/tree/master/.github/welcome

Hi, @anshgoyalevil . Please take a look at this welcome comment. As you can see the picture is lost somehow. May you check and solve this issue?

**Comment by ShivangShandilya** [comment]
> > @Aisuko
> > Could you please specify the issue description a bit more. Since, the welcome pictures are already present in this repo at https://github.com/meshery/meshery-operator/tree/master/.github/welcome
> 
> Hi, @anshgoyalevil . Please take a look at this welcome comment. As you can see the picture is lost somehow. May you check and solve this issue?

@Aisuko I checked again but the pictures are already present 🤔. Can you check other repositories and share the exact welcome picture you think is missing here? 😊
Thank You

**Comment by anshgoyalevil** [comment]
> > @Aisuko
> > Could you please specify the issue description a bit more. Since, the welcome pictures are already present in this repo at https://github.com/meshery/meshery-operator/tree/master/.github/welcome
> 
> Hi, @anshgoyalevil . Please take a look at this welcome comment. As you can see the picture is lost somehow. May you check and solve this issue?

Could you please share the link to welcome comment you are referencing here.
Also, I rechecked the Welcome Images, and they are already present.

**Comment by Aisuko** [comment]
https://github.com/meshery/meshery-operator/pull/464#issuecomment-1528988064

**Comment by Aisuko** [comment]
Hi, @ShivangShandilya @anshgoyalevil  thanks for your keep tracking on this issue. The picture is in the correct location, but it failed to render. Please take a look at https://github.com/meshery/meshery-operator/pull/464#issuecomment-1528988064

**Comment by anshgoyalevil** [comment]
@Aisuko 

It's working for me.

![image](https://user-images.githubusercontent.com/94157520/236657744-877eff55-118a-44b3-b339-738e095c6eba.png)

**Comment by anshgoyalevil** [comment]
@Aisuko 

Actually, this issue is neither on your network, nor anybody else's.

It is GitHub which have a DNS issue, and due to that, almost every picture on GitHub behaves like this.

**Comment by ShivangShandilya** [comment]
Thank you for explaining the issue @anshgoyalevil 😊.

**Comment by Aisuko** [comment]
I see. Thank you, guys. I will close this issue.
