### ISSUE TITLE
CI: The build test is not working and it should be fixed.

### ISSUE THREAD

**Issue by Aisuko** [meshery/meshery-operator#474]
#### Current Behavior

The current build checking step has a condition below
https://github.com/meshery/meshery-operator/blob/27cfe5f0a3df642b88681bbac252e98757885749/.github/workflows/approve-to-run-ci.yml#L53

However, even though the PR was approved or the comment includes an LGTM. The CI is still not being triggered. 

#### Expected Behavior

The CI can be triggered by LGTM/approved, or we can add requirements for it after `codecov` and `golangci-lint` were successful.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by duckling69** [comment]
Hey @Aisuko I'd like to work on this issue

**Comment by Aisuko** [comment]
@duckling69 thank you.

**Comment by duckling69** [comment]
Hey @Aisuko i think i got what the issue was basically 

![image](https://github.com/meshery/meshery-operator/assets/85884487/adef37a9-de26-4ede-afd8-43f3c21d089a)

**github.event_name == 'pull_request' & github.event.pull_request.body**  were only looking at body of initial PR comment not for comments added afterwards so i used issue_comment to trigger it when comment is added after initial pr 
also added need for build so it always run after `codecov` and `golint` has run

**Comment by Aisuko** [comment]
> Hey @Aisuko i think i got what the issue was basically
> 
> ![image](https://user-images.githubusercontent.com/85884487/238565815-adef37a9-de26-4ede-afd8-43f3c21d089a.png)
> 
> **github.event_name == 'pull_request' & github.event.pull_request.body** were only looking at body of initial PR comment not for comments added afterwards so i used issue_comment to trigger it when comment is added after initial pr also added need for build so it always run after `codecov` and `golint` has run

Hi, @duckling69 thanks for your clarify.
