### ISSUE TITLE
Meshery Operator to re-configure Meshsync Informer

### ISSUE THREAD

**Issue by Azanul** [meshery/meshery-operator#479]
#### Current Behavior
Meshsync informer watches every component (ConfigMap, Pods, etc).

#### Desired Behavior
Meshsync informer should be configurable by the user.

#### Implementation
Phase 1: 
- the configuration will be a simple blacklist of components to not watch

Phase 2:
- the configuration will be a separate object that will include the components to watch, a timeout per component (TBD).

#### Acceptance Tests
User should be able to configure which components to watch and how frequently to receive updates from Meshsync regarding them.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Azanul** [comment]
@leecalcote @Aisuko

**Comment by leecalcote** [comment]
In phase 1, it’s acceptable that users are required to directly configure the custom resource via kubectl. Will you also please open an issue in the Meshery repo for UX design of the Environment tab on the Settings, page to provide users with the user interface in which they can configure MeshSync settings per Kubernetes cluster? // @avantikajain289

**Comment by Azanul** [comment]
> In phase 1, it’s acceptable that users are required to directly configure the custom resource via kubectl. Will you also please open an issue in the Meshery repo for UX design of the Environment tab on the Settings, page to provide users with the user interface in which they can configure MeshSync settings per Kubernetes cluster? // @avantikajain289

removed `HTTP endpoints for communicating with server` from Phase 1.
