### ISSUE TITLE
Meshery Logo Missing On Successful Contribution Email

### ISSUE THREAD

**Issue by yashchaddha** [meshery/meshery-operator#493]
#### Current Behavior

Meshery Logo Missing in email of Successful Contribution
<img width="401" alt="image" src="https://github.com/meshery/meshery-operator/assets/25150314/7af84d98-b600-48e3-b037-dd0bcf1f76b9">

#### Expected Behavior

Logo Should be Visible
Link Pasted in config.yml is https://raw.githubusercontent.com/meshery/meshery-operator/master/.github/welcome/meshery-celebration-dark.svg
This returns 404 error

While the link should be https://raw.githubusercontent.com/meshery/meshery-operator/master/.github/welcome/mesherycelebration-dark.svg

This will return 
<img width="347" alt="image" src="https://github.com/meshery/meshery-operator/assets/25150314/2da3e658-73b1-46f9-83af-04eed01c95a1">

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.meshery.io)

**Comment by leecalcote** [comment]
Perfect. Thank you.
