### ISSUE TITLE
[Docs] add link to and description of MeshSync in readme

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-operator#508]
#### Desired State

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.meshery.io)

**Comment by Ghat0tkach** [comment]
I'll take this one😶‍🌫️

**Comment by Ghat0tkach** [comment]
I have merged the PR in my master branch to give a view of readme file . I didnt knew by doing so , it will close this issue 😅
