### ISSUE TITLE
[Docs] readme: use Meshery logo with tagline 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-operator#510]
#### Desired State

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.meshery.io)

**Comment by jiyanpatil07** [comment]
Hello @leecalcote ,
I would like to work on the issue.
Can you please provide description of current state and desired state for this issue.
Thank You.

**Comment by leecalcote** [comment]
// @Ghat0tkach

**Comment by Ghat0tkach** [comment]
@jiyanpatil07 
The current logo is outdated and most importantly it lacks our tagline , The current behaviour should be replacement of logo and addition of our tagline

for logo please refer to meshery/meshery repository and for tagline refer to https://meshery.io/cloud-native-management/meshery

**Comment by rj2704** [comment]
Hi @Ghat0tkach, I can fix this issue. If no one is working on this problem, please assign it to me.

**Comment by jiyanpatil07** [comment]
@rj2704 Hello Jiger,
I'm on the issue currently,
I will assign you if I get stuck or anything.
Thank YOu.

**Comment by Ghat0tkach** [comment]
@jiyanpatil07 updates?

**Comment by jiyanpatil07** [comment]
@Ghat0tkach,
I'm traveling since couple of days.
I would suggest to assign it to @rj2704 for early solution.
Really Sorry.

**Comment by rj2704** [comment]
@jiyanpatil07 no worries.
@Ghat0tkach Assign it to me, and I will fix it.

**Comment by Ghat0tkach** [comment]
@rj2704 , there you go

**Comment by rj2704** [comment]
Hi, @Ghat0tkach  I have to add the below tagline for Meshery, correct?

A self-service engineering platform, [Meshery](https://meshery.io/), is the open source, cloud native manager that enables the design and management of all Kubernetes-based infrastructure and applications. Among other features, As an extensible platform, Meshery offers visual and collaborative GitOps, freeing you from the chains of YAML while managing Kubernetes multi-cluster deployments.

**Comment by rj2704** [comment]
Hi @Ghat0tkach, Please review these PRs if you have the time. In that case, we can merge it if everything seems fine.
