### ISSUE TITLE
[Docs] readme: support light and dark mode image versions of Meshery logo

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-operator#511]
#### Desired State

See the other repositories for an example. 

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.meshery.io)

**Comment by Rajdeep1311** [comment]
Can you please tell me details of what is to be done, sir?

**Comment by Ghat0tkach** [comment]
hey @Rajdeep1311 , 
The current meshery logo stays same in both light mode and dark mode , However it should be mode-specific
For example , please refer to https://github.com/meshery/meshery readme and notice the logo behavior in both light and dark mode

**Comment by Rajdeep1311** [comment]
> hey @Rajdeep1311 , 
> The current meshery logo stays same in both light mode and dark mode , However it should be mode-specific
> For example , please refer to https://github.com/meshery/meshery readme and notice the logo behavior in both light and dark mode

Okay sir... I will check and try to help you out

**Comment by Rajdeep1311** [comment]
Sir, the readme shows no Meshery logo but the CNCF logo does not load in dark mode

**Comment by Rajdeep1311** [comment]
![image](https://github.com/meshery/meshery-operator/assets/113296626/e6ae65c4-59cf-455f-90ab-0a480a41a6a5)

Should I change this?

**Comment by Ghat0tkach** [comment]
> ![image](https://github.com/meshery/meshery-operator/assets/113296626/e6ae65c4-59cf-455f-90ab-0a480a41a6a5)
> 
> Should I change this?

Meshery logo is top of readme

**Comment by Rajdeep1311** [comment]
![image](https://github.com/meshery/meshery-operator/assets/113296626/83dd83e1-4c71-4ff5-8c40-d04dcfa56600)

Sir the logo isn't loading, it is not because of the internet speed.
But I have changed it on my local for both the mode

![image](https://github.com/meshery/meshery-operator/assets/113296626/e0e88c9b-5fc6-4870-a24a-eed829097d76)

![image](https://github.com/meshery/meshery-operator/assets/113296626/22ec03d7-7861-4767-97d0-0ad41e45335c)

**Comment by Rajdeep1311** [comment]
Sir  I have raised a PR #513

**Comment by Ghat0tkach** [comment]
@leecalcote , Apologies I didn't recheck the issue , however it seems like readme logo is already compatible for both themes
![image](https://github.com/meshery/meshery-operator/assets/59855919/966fdbad-e92f-4fdb-a43a-fd922125e202)

![image](https://github.com/meshery/meshery-operator/assets/59855919/c484d8ff-8249-4f32-a4e2-4c315879755f)

**Comment by OmAximani0** [comment]
> @leecalcote , Apologies I didn't recheck the issue , however it seems like readme logo is already compatible for both themes 

Yes I have seen this happening sometimes if there is a network issue the logo and media doesn't loads properly you just have to refresh the page or check the network
