### ISSUE TITLE
[Documentation] update the CONTRIBUTING.md with Issues & Pull Requests sections

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery-operator#522]
Link to issue: [meshery-operator](https://github.com/layer5io/layer5/issues/4932)

**Comment by sandramsc** [comment]
Hi, _(only if there's a need to do so in this case)_ can I have this issue assigned to me, please?

- currently working on this issue in the Meshery repo, creating a new issue in each repo mentioned so as to effectively maintain the procedure of creating an issue and thereafter a PR that closes it.

**Comment by Aisuko** [comment]
Hi @sandramsc . Here is the contributing document https://docs.meshery.io/project/contributing. It not in `Meshery-operator` repo. And I think we do not need to open a PR in here.

**Comment by sandramsc** [comment]
> Hi @sandramsc . Here is the contributing document https://docs.meshery.io/project/contributing. It not in `Meshery-operator` repo. And I think we do not need to open a PR in here.

Hi @Aisuko thanks for pointing this out, will update the main issue a well.

**Comment by sandramsc** [comment]
Hi @Aisuko thanks for pointing this out, will update the main issue a well.
