### ISSUE TITLE
[README.md] bold styling not applied to text

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery-operator#523]
#### Current State
Currently all points under section: "Join the Meshery community!" have the first word or two italicized and bold styling added. However the third point "_Fill-in_ a [community member form](https://layer5.io/newcomers) to gain access to community resources.", has its first word "Fill-in" italicized, but does not have the bold styling applied. 

### Screenshots
![imageedit_3_9131638095](https://github.com/meshery/meshery-operator/assets/19821445/e4419ebe-0681-4a87-bd26-65d6f564bc1e)

#### Desired State
To maintain consistency, add bold styling to the text "Fill-in"

i.e "_**Fill-in**_  a [community member form](https://layer5.io/newcomers) to gain access to community resources."

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.meshery.io)

**Comment by hemantmm** [comment]
Hi, @sandramsc can I work on this issue?

**Comment by hemantmm** [comment]
Hi, @Ghat0tkach how can  @rohan472000 open the PR without asking?

**Comment by Mohith234** [comment]
Hey @hemantmm, A fair warning to @rohan472000

Thanks for volunteering to work on the issue. I would suggest finding another issue to work on as this is a small fix.

// @hemantmm @rohan472000

**Comment by rohan472000** [comment]
> Hey @hemantmm, A fair **warning** was given to @rohan472000


I expect positive words and constructive tone from the community, I've accepted my negligence of contributing guidelines and gave reasons ([here](https://github.com/meshery/meshery-operator/pull/524#pullrequestreview-1641030021)) also.

**Comment by leecalcote** [comment]
@hemantmm, let's get you a new issue to work on... a number of new "help wanted" issues were recently created and might be up your alley --> https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

**Comment by leecalcote** [comment]
@hemantmm I'll tag you on a couple to see if they are of interest.

**Comment by leecalcote** [comment]
> > Hey @hemantmm, A fair **_warning_** was given to @rohan472000
> 
> I expect positive words and constructive tone from the community, I've accepted my negligence of contributing guidelines and gave reasons ([here](https://github.com/meshery/meshery-operator/pull/524#pullrequestreview-1641030021)) also.

Yes, you did, @rohan472000, and the reviewers here have faithfully stewarded in accordance with community/project norms. Thanks for this.

What you have not done, however, is offer an apologetic word to @hemantmm. For my part, I consider that a short, but sweet couple of words would go a long way.

**Comment by rohan472000** [comment]
Yeah sure @leecalcote , I apologize for any inconvenience my previous actions may have caused and assure @hemantmm it was not my intention to create such a situation :)

**Comment by leecalcote** [comment]
@rohan472000 have we found you your next issue to tackle, yet? Let me know if I can help identify one.

**Comment by rohan472000** [comment]
No @leecalcote , appreciate if you can help me with that.

**Comment by Mohith234** [comment]
Hey @rohan472000, You can look at the good first issues [here](https://github.com/layer5io/layer5/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee). Find one you would like to work with, comment under it and ping me on slack so that I could assign it to you.

P.S. I will tag you in some of the issues if you would be interested let me know. Also let's cut the discussion here on this PR and move the discussion to slack

Thank You
